Neos:
  Flow:
    error:
      debugger:
        ignoredClasses:
          'Neos\\ContentGraph\\DoctrineDbalAdapter.*': true
  EventSourcing:
    EventListener:
      listeners:
        'Neos\ContentGraph\DoctrineDbalAdapter\Domain\Projection\GraphProjector':
          eventStore: 'ContentRepository'
